openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger OpenDAX
components:
  schemas:
    general:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
          format: uri
      required:
        - name
        - url
      example:
        name: OpenDAX
        url: https://www.opendax.io/
    frontend:
      type: object
      properties:
        theme:
          type: string
          default: "blue"
          enum:
            - blue
            - teal
            - red
        layout:
          type: object
          properties:
            draggable:
              type: boolean
              default: false
            resizable:
              type: boolean
              default: false
        landing:
          type: boolean
          default: true
    security:
      type: object
      properties:
        csrf:
          type: boolean
          default: true
        tls:
          type: object
          properties:
            enabled: 
              type: boolean
              default: true
            domain:
              type: string
              format: uri
            email:
              type: string
              format: email
    kyc:
      type: object
      properties:
        brarong:
          type: object
          properties:
            status:
              type: boolean
              default: true
        kycaid:
          type: object
          properties:
            status:
              type: boolean
              default: false
            auth_token:
              type: string
              default: b638c7d108ffb3443a2b0f87033c1b7a78f1
        kyc_steps:
          type: object
          properties:
            email:
              type: boolean
              readOnly: true
              default: true
            phone:
              type: boolean
              default: true
            profile:
              type: boolean
              default: true
            document:
              type: boolean
              default: true
            address:
              type: boolean
              default: true
        required_levels:
          type: object
          properties:
            deposit:
              type: integer
              format: int64
              default: 1
            withdrawal:
              type: integer
              format: int64
              default: 1
            trading:
              type: integer
              format: int64
              default: 1
    analytics: 
      type: object
      properties:
        google:
          type: object
          properties:
            status:
              type: boolean
              default: false
            tracker_key:
              type: string
    captcha:
      type: object
      properties:
        provider:
          type: string
          default: recaptcha
          enum:
            - recaptcha
            - geetest
        site_key:
          type: string
        secret_key:
          type: string
    sms:
      type: object
      provider:
        provider:
          type: string
          default: twilio
          readOnly: true
        account_sid:
          type: string
        auth_token:
          type: string
        phone:
          type: string
    mailer:
      type: object
      properties:
        url:
         type: string
        user:
         type: string
        password:
         type: string
         format: password
    storage:
      type: object
      properties:
        status:
          type: boolean
          default: false
        provider:
          type: string
          default: google
          enum:
            - google
            - s3
        base_url:
          type: string
          format: uri
          default: storage.apis.google.com
        bucket_name:
          type: string
          default: example-bucket
        region:
          type: string
          default: us-west-1
        access_key:
          type: string
        secret_key:
          type: string